### ISSUE TITLE
Ask for Didispeech Dataset

### ISSUE THREAD

**Issue by 980202006** [sos1sos2Sixteen/sos1sos2Sixteen.github.io#1]
I saw the VoiceLens you introduced in github.io. Its idea is great, and I want to try adding it to my own tts module.
Can you share the didispeeh1 and 2 datasets? I want to use it for experiments, but the official website application link is no longer 
available.

**Comment by sos1sos2Sixteen** [comment]
i too no longer have access to this dataset. i'd recommend libritts-R instead, the downside is it has less speaker informations.

**Comment by 980202006** [comment]
Thank you!
